binutils-cross-canadian: Add lib*.a files to the staticdev package
This fixes the following QA issue when building an SDK for
x86_64-mingw32 machines.

ERROR: binutils-cross-canadian-x86-64-2.36.1-r0 do_package_qa: QA Issue: non -staticdev package contains static .a library: binutils-cross-canadian-x86-64 path '/usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-w64-mingw32/usr/lib/x86_64-nilrt-linux/bfd-plugins/libdep.dll.a' [staticdev]

Upstream-Status: Pending

Signed-off-by: Shruthi Ravichandran <shruthi.ravichandran@ni.com>
(cherry picked from commit 4e1871f492e8f73371ae3083dcad530f5a50a6df)
Signed-off-by: Alex Stewart <alex.stewart@ni.com>